
server:
  port: 8081

spring:
  application:
    name: activity-app


  data:
    mongodb:
      uri: mongodb://localhost:27017/activity_db
      database: activity_db

logging:
  level:
    org.springframework.security: DEBUG