
server:
  port: 8081

spring:
  application:
    name: activity-app

  data:
    mongodb:
      uri: mongodb://localhost:27017/activity_db
      database: activity_db

jwt:
  secret: ${JWT_SECRET:ChangeThisSecretInProduction1234567890123456}
  expirationMillis: 86400000

logging:
  level:
    org.springframework.security: DEBUG